In [20]:
from numpy import *
from numpy.linalg import det 
from numpy.linalg import eig, inv

In [4]:
data = [4.0, 1.0, 2.0]
v = array ( data )

print(v)

[4. 1. 2.]


In [5]:
v = array([3,2])
w = array([2, -1])

v_plus_w = v + w

print(v_plus_w)

[5 1]


In [6]:
v = array ([3, 1])
scaled_v = 2.0 * v

print(scaled_v)

[6. 2.]


In [24]:
i_hat = array([2,0])
j_hat = array([0,3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
#print(basis)

# declare vector v 0
v = array([2,1])

# create new vector w
# by transforming v with dot product
w = basis.dot(v)

print(w)

[4 3]


In [20]:
print(basis*v)

[[4 0]
 [0 3]]


In [27]:
i_hat = array([-1, 0])
j_hat = array([ 0,-4])

basis = array( [i_hat, j_hat]).transpose()

v = array([4,2])
w = basis.dot(v)
print(w)

[-4 -8]


### Sheers, Rotations, and Inversions

In [31]:
from numpy import array
i_hat = array([1, 2])
j_hat = array([-4, -1])
basis = array([i_hat, j_hat]).transpose ()
v = array ([1,1])
w = basis.dot(v)
print (w)

[-3  1]


### The Determinant

In [32]:
i_hat = array( [3, 0])
j_hat = array( [0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # prints 6.0

6.0


In [33]:
i_hat = array([1, 0])
j_hat = array([1, 1])
basis = array([i_hat, j_hat]).transpose ()
determinant = det(basis)

print(determinant)

1.0


In [34]:
i_hat = array([1, 2])
j_hat = array([-2, 1])
basis = array([i_hat, j_hat]).transpose ()
determinant = det(basis)

print(determinant)

5.000000000000001


In [35]:
i_hat = array([-1, 1])
j_hat = array([1, -1])
basis = array([i_hat, j_hat]).transpose ()
determinant = det(basis)

print(determinant)

0.0


In [41]:
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations
combined = transform2 @ transform1
print (combined)

[[ 1 -1]
 [ 1  0]]


### Dot Products

In [45]:
from numpy import array
v = array([3, 2])
w = array ([2,-1])
dot_product1 = w.dot(v)
dot_product2 = v.dot(w)
print(dot_product1, dot_product2) # prints 4.0

4 4


In [46]:
# Matrix Dot product
i_hat = array([-1, 2])
j_hat = array ([3, 1])
basis = array([i_hat, j_hat]).transpose()
v = array([1, 1])
dot_product = basis.dot(v)
print(dot_product) # prints [2, 3]

[2 3]


Over and Down. Over and Down!
To avoid doing a whole bunch of projection work, it is much easier to calculate matrix dot products by hand using the "over and down!" attern. Multiply and sum each row with each respective column, and this will quickly and efficiently apply a series of transformations.

In [50]:
v = array([[3, 1], 
          [2, 0]])
w = array([[1, 2, 0], 
          [3, 1, 1]])
dot_product = v.dot(w)
print (dot_product)

[[6 7 1]
 [2 4 0]]


### Systems of Linear Equations and Inverse Matrices

Solving Systems of Equations
Let's say you have a system of equations like this:

4x+2y+4z = 44
5x+3y+7z = 56
9x+3y+6z = 72


We need to solve for x, y, and z. First let's declare the equations above as three matrices:
A = [[4,2,4], [5,3,7], [9,3,6]]
x = [x,y,z]
B = [44, 56, 72]

We need to transform matrix A with some other vector X that will result in vector B.

AX = B

We can isolate X by multiplying each side with the inverse of matrix A, which we will call A^(-1)

In [52]:
from numpy.linalg import inv
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
print(inv(A))

[[-0.5         0.          0.33333333]
 [ 5.5        -2.         -1.33333333]
 [-2.          1.          0.33333333]]


In [62]:
identity = inv(A).dot(A)
print(identity)

[[ 1.00000000e+00 -2.22044605e-16 -4.44089210e-16]
 [ 2.66453526e-15  1.00000000e+00  1.77635684e-15]
 [-6.66133815e-16 -2.22044605e-16  1.00000000e+00]]


In [61]:
result = A @ inv(A)
print(result)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [64]:
B = array([44, 56, 72])
print(B)

[44 56 72]


In [67]:
print(inv(A))

[[-0.5         0.          0.33333333]
 [ 5.5        -2.         -1.33333333]
 [-2.          1.          0.33333333]]


In [70]:
x = inv(A) @ B
print(x)

[ 2. 34. -8.]


In [71]:
# 4X + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
[4, 2, 41],
[5, 3, 71],
[9, 3, 61]
])

B = array([
44,
56,
72
])

X = inv(A).dot(B)

print(X)

[ 1.85714286 35.85714286 -0.85714286]


### Matrix Decomposition

Matrix decomposition is breaking up a matrix into its basic components, much like factoring numbers (e.g. 10 can be factored to 2 x 5).

Matrix decomposition is helpful for tasks like finding inverse matrices, calculating determinants, as well as linear regression.

There are many ways to decompose a matrix, but the most common method is eigendecomposition, which is often used for machine learning and Principal Component Analysis (РСА).

At this level, just know eigendecomposition is helpful for breaking up a matrix into components that are easier to work with in different machine learning tasks.

Eigendecomposition

If we have a square matrix A, it has the following eigenvalue equation:

Av = 20

If A is the parent matrix, it has eigenvector v and eigenvalue 2 (lambda).

There is one eigenvector and eigenvalue for each dimension of the parent matrix, and not all matrices can be decomposed into an eigenvector and eigenvalue.

Sometimes complex (imaginary) numbers will result! To the right is how we calculate eigenvectors and eigenvalues in NumPy for a given matrix A.

In [75]:
# Eigendecomposition
from numpy import array, diag 
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("'EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS" )
print(eigenvecs)

'EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [76]:
from numpy import array, diag 
from numpy. linalg import eig, inv

A = array([
[1, 2],
[4, 5]
])

eigenvals, eigenvecs = eig(A)
print ("EIGENVALUES")
print(eigenvals)
print(" \nEIGENVECTORS")
print (eigenvecs)
print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q.dot(L).dot(R)
print(B)

EIGENVALUES
[-0.46410162  6.46410162]
 
EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]


## Exercises
1. Vector v has a value of [1, 2] but then a transformation happens. i lands at [2, 0] and j lands at [0, 1.5]. Where does v land?
2. Vector v has a value of [1, 2] but then a transformation happens. i lands at [-2, 1] and j lands at [1, -2]. Where does v land?
3. A transformation i lands at [1, 0] and j lands at [2, 2]. What is the determinant of this transformation?
4. Can two or more linear transformations be done in single linear transformation? Why or why not?
5. Solve the system of equations for x, y, and z:
3x+1y+0z= =54 2x + 4y + 1z = 12 3x + 1y + 8z = 6
6. Is the following matrix linearly dependent? Why or why not?
21 63

In [27]:
from numpy import array
i_hat = array([2, 0])
j_hat = array([0, 1.5])
basis = array([i_hat, j_hat]).transpose ()
# print(basis)
# declare vector v 0
v = array([1,2])

# create new vector w
# by transforming v with dot product
w = basis.dot(v)

print(w)

[2. 3.]


[ 2, 1.5 ]

2 task

In [25]:
from numpy import array
i_hat = array([-2, 1])
j_hat = array([1, -2])
basis = array([i_hat, j_hat]).transpose ()
print(basis)

[[-2  1]
 [ 1 -2]]


In [12]:
# declare vector v 0
v = array([1,2])

# create new vector w
# by transforming v with dot product
w = basis.dot(v)

print(w)

[ 0 -3]


3 task

In [16]:
i_hat = array([1,0])
j_hat = array([2,2])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
print(det(basis))

2.0


4 task

q: Can two or more linear transformations be done in single linear transformation? Why or why not?

a: you can have different linear transformation at the same time: scaling, rotating, shearing, inversioning.


In [21]:
#5 task
# 3x + 1y + 0z = 54 
# 2x + 4y + 1z = 12 
# 3x + 1y + 8z = 6

my_matrix = array([[3,1,0],
                   [2,4,1],
                   [3,1,8]
                  ])
#print(my_matrix)
target = array([54,12,6])

x = inv(my_matrix).dot(target)

print(x)

[19.8 -5.4 -6. ]
